import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Link from "next/link";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        style={{
          margin: 0,
          backgroundColor: "#f5f5f5",
          color: "#111111",
          fontFamily: "sans-serif",
        }}
      >   
        <header
          style={{
            backgroundColor: "#111",
            padding: "20px 40px",
          }}
        >
          <div
            style={{
              maxWidth: "1000px",
              margin: "0 auto",
              display: "flex",
              justifyContent: "space-between",
              alignItems: "center",
            }}
          >
            <Link
              href="/"
              style={{
                color: "white",
                textDecoration: "none",
                fontSize: "24px",
                fontWeight: "bold",
              }}
            >
              Tech Blog
            </Link>

            <nav
              style={{
                display: "flex",
                gap: "20px",
              }}
            >
              <Link
                href="/"
                style={{
                  color: "white",
                  textDecoration: "none",
                }}
              >
                HOME
              </Link>

              <Link
                href="/blog"
                style={{
                  color: "white",
                  textDecoration: "none",
                }}
              >
                BLOG
              </Link>

              <Link 
                href="/calendar"
                style={{
                  color: "white",
                  textDecoration: "none"
                }}
              >
                APP
              </Link>
            </nav>
          </div>
        </header>

        <main>{children}</main>
        <footer
          style={{
          backgroundColor: "#111",
          color: "#aaa",
          padding: "30px 20px",
          marginTop: "60px",
          }}
>
        <div
          style={{
          maxWidth: "1000px",
          margin: "0 auto",
          textAlign: "center",
          lineHeight: "1.8",
          }}
  >
        <p>Tech Blog</p>

        <p style={{ fontSize: "14px" }}>
          アラフォー薬剤師がITエンジニア転職を目指して
          学習記録と個人開発を発信中。
        </p>

        <p
          style={{
          fontSize: "12px",
          marginTop: "16px",
          }}
    >
        © 2026 Tech Blog
        </p>
        </div>
        </footer>
      </body>
    </html>
  );
}
